평면의 두 점의 좌표가 주어져 있을 때 두 점을 지나는 직선의 방정식을 출력하는 프로그램을 작성

In [40]:
def funcX(p1, p2):
  a = (p1[1] - p2[1] / p1[0] - p2[0])
  b = p1[1] - a*p1[0]
  return a, b

a, b = funcX((1, 2), (2, 4))
print(f"y = {a}x + {b}")

y = -4.0x + 6.0


In [41]:
# overloading in Python

def funcX(p1, p2):
  a = (p1[1] - p2[1] / p1[0] - p2[0])
  b = p1[1] - a*p1[0]
  return a, b

a, b = funcX((1, 2), (2, 4))
print(a, b)

# 같은 이름의 함수가 다음에 선언되면 오버로딩되어 마지막에 선언된 형태로 동작
def funcX(x):
  y = a*x + b
  return y

y = funcX(7)
print(y)

y = {funcX(x) for x in range(10)}
print(y)


-4.0 6.0
-22.0
{2.0, -30.0, 6.0, -26.0, -22.0, -18.0, -14.0, -10.0, -6.0, -2.0}


In [42]:
# List 형태의 데이터 확인
myList = [19, 15, 20, 12, 27, 28, 11, 31]
myList.append(len(myList))

print(myList.pop())

8


# Numpy

In [43]:
import numpy as np

In [44]:
listA = [0, 1, 2, 3, 4, 5]
# List를 numpy를 통핸 array 형태로 변형
arrayA = np.array(listA)

# List와 Array 확인
print(f"list: {listA}")
print(f"Array: {arrayA}")

list: [0, 1, 2, 3, 4, 5]
Array: [0 1 2 3 4 5]


In [45]:
# array 연산 vs list 연산
# list 연산은 두 list 원소를 모두 포함시켜서 합침
# array 연산은 같은 위치의 원소끼리 덧셈

listA = [0, 1, 2, 3, 4, 5]
arrayA = np.array(listA)

listB = [6, 7, 8, 9, 3, 5]
arrayB = np.array(listB)

addList = listA + listB
addArray = arrayA + arrayB

print(f"Array: {addList}")
print(f"Array: {addArray}")

Array: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 3, 5]
Array: [ 6  8 10 12  7 10]


In [46]:
# 평면의 두 점의 좌표

def funcX(p1, p2):
  delta = p1 - p2
  a = delta[1] / delta[0]
  b = p1[1] - a*p1[0]
  return a, b

a, b = funcX(np.array([1, 2]), np.array([2, 4]))
print(f"y = {a}x + {b}")

y = 2.0x + 0.0


In [47]:
# 차원 확장
import numpy as np
listA = [[0, 1, 2], [3, 4, 5]]
arrayA = np.array(listA)

listB = [[6, 7, 8], [9, 3, 5]]
arrayB = np.array(listB)

addList = listA + listB
addArray = arrayA + arrayB

# List는 데이터 값을 더하는게 아닌, 리스트 자체를 이어 붙인다.
# Array는 해당 Array의 데이터 값을 사칙연산이 가능

print(f"list: {addList}")
print(f"array : {addArray}")

list: [[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 3, 5]]
array : [[ 6  8 10]
 [12  7 10]]


In [48]:
# 정보 확인
arrayA = np.array([[[0, 1], [1, 2]], [[3, 4], [4, 5]]])
arrayB = np.array([[[6, 7], [7, 8]], [[9, 3], [3, 5]]])

addArray = arrayA + arrayB
mulArray = arrayA * arrayB

print(f"Add : {addArray}")
print(f"Mul : {mulArray}")
print()

print(f"Dimensions: {arrayA.ndim}")
print(f"Shape : {addArray.shape}")
print(f"Data type : {mulArray.dtype}")

Add : [[[ 6  8]
  [ 8 10]]

 [[12  7]
  [ 7 10]]]
Mul : [[[ 0  7]
  [ 7 16]]

 [[27 12]
  [12 25]]]

Dimensions: 3
Shape : (2, 2, 2)
Data type : int64


In [49]:
#matrix와 array

listA = [[1, 2], [4, 5]]
arrayA = np.array(listA)
matrixA = np.matrix(listA)

listB = [[6, 8], [3, 5]]
arrayB = np.array(listB)
matrixB = np.matrix(listB)

addArray = arrayA + arrayB
addMatrix = matrixA + matrixB

print(f"array + : {addArray}")
print(f"matrix + : {addMatrix}")

mulArray = arrayA * arrayB
mulMatrix = matrixA * matrixB

# matrix는 행렬의 곱연산으로 작동
print(f"array * : {mulArray}")
print(f"matrix * : {mulMatrix}")

array + : [[ 7 10]
 [ 7 10]]
matrix + : [[ 7 10]
 [ 7 10]]
array * : [[ 6 16]
 [12 25]]
matrix * : [[12 18]
 [39 57]]


# numpy 배열 생성 함수



*   array() -> list를 array로 변환

*   arange() -> 일정 간격수로 array 생성

*   ones() -> 1로 채운 n차원 array 생성

*   zeros() -> 0으로 채운 array 생성

*   empty() -> 빈 array 생성

*   eye() -> 대각선 1 그외 0

*   identity() -> eye()와 동일

*   linespae() -> 균등 간격 array 생성

*   full() -> 특정 값으로 채운 array 생성












In [50]:
a = np.zeros(2)
print('a\n', a)
b = np.zeros((2, 2))
print('b\n', b)
c = np.ones((2, 3))
print('c\n', c)
d = np.full((2, 3), 5)
print('d\n', d)
e = np.eye(3)
print('e\n', e)

a
 [0. 0.]
b
 [[0. 0.]
 [0. 0.]]
c
 [[1. 1. 1.]
 [1. 1. 1.]]
d
 [[5 5 5]
 [5 5 5]]
e
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Numpy 자료형과 속성

In [51]:
# array 생성 시 데이터 타입 지정 가능
arrayFloat64 = np.array([1, 2], dtype=np.float64)
print(arrayFloat64.dtype)

arrayFloat64 = arrayFloat64.astype(np.int8)
print(arrayFloat64.dtype)

float64
int8


In [52]:
array = np.array([[0, 1, 2], [3, 4, 5]])

print('type(array) : ', type(array)) # arrya의 type 출력
print('array.ndim:',array.ndim) # 차원 출력
print('array.dtype:',array.dtype) # array 안의 데이터 타입 출력
print('array.itemsize:',array.itemsize) # 배열 요소의 각 원소의 byte 크기 int니까 8byte
print('array.size:',array.size) # array 데이터 크기 출력
print('array.nbytes:',array.nbytes) # int 데이터이니, itemsize 8bytes * size 6
print('array.T:\n',array.T) # 행렬을 transpose 해서 출력

print('array.shape:',array.shape)

type(array) :  <class 'numpy.ndarray'>
array.ndim: 2
array.dtype: int64
array.itemsize: 8
array.size: 6
array.nbytes: 48
array.T:
 [[0 3]
 [1 4]
 [2 5]]
array.shape: (2, 3)


In [53]:
a = np.array([[0, 1, 2], [3, 4, 5]])
print('a\n', a)

# transpose 방법 2가지
b = a.transpose()
print('b\n', b)
c = a.T
print('c\n', c)

a
 [[0 1 2]
 [3 4 5]]
b
 [[0 3]
 [1 4]
 [2 5]]
c
 [[0 3]
 [1 4]
 [2 5]]


# Numpy Array

In [54]:
a = np.arange(8) # 1행 8열 array 생성
print('a\n', a)

a.shape = (2, 4) #차원을 2행 4열로 바꿈
print('shape\n', a)

print('flatten\n', a.flatten()) # 1차원으로 펼쳐줌 = flatten

a.resize((4, 2)) #차원을 4행 2열로 바꿈
print('resize\n', a)

a
 [0 1 2 3 4 5 6 7]
shape
 [[0 1 2 3]
 [4 5 6 7]]
flatten
 [0 1 2 3 4 5 6 7]
resize
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [55]:
mask = np.array([0, 1, 1, 0], dtype=bool) # array Mask 생성
print('mask\n', mask)

data = np.random.randn(4, 2)
print('\ndata 원본\n', data)

# mask는 0, 1, 1, 0 이므로
# data[mask]는 두 번째, 세 번째 데이터만 True로 남고
print('\n[0, 1, 1, 0] masking\n', data[mask])
# data[~mask]는 첫 번째, 네 번째 데이터만 False의 역 = True 로 남는다.
print('\ninverse masking\n', data[~mask])

# 0보다 큰 데이터 추출
posit = data[data > 0]
print(' > 0\n', posit)

over1 = data[1][data[1] > 0]
print('data[1] and > 0\n', over1)

mask
 [False  True  True False]

data 원본
 [[-0.45919401  0.60636681]
 [ 0.87687242 -1.13189418]
 [-1.04647143  1.48745725]
 [-0.65672608  0.02567622]]

[0, 1, 1, 0] masking
 [[ 0.87687242 -1.13189418]
 [-1.04647143  1.48745725]]

inverse masking
 [[-0.45919401  0.60636681]
 [-0.65672608  0.02567622]]
 > 0
 [0.60636681 0.87687242 1.48745725 0.02567622]
data[1] and > 0
 [0.87687242]


In [56]:
origin = np.arange(6)
print('origin\n', origin)

copy = origin
print('copy\n', copy)

deepCopy = origin.copy()
print('deepCopy\n', deepCopy)

# 원본이 변형되면 일반 copy와 원본은 값이 변경
# deepCopy의 데이터는 변화 X
origin[1] = 10
print('\nchanging origin data\n')
print('origin\n', origin)
print('copy\n', copy)
print('deepCopy\n', deepCopy)

# 원본을 복사한 copy 값이 변경되면?
# 원본 array의 데이터 값도 변경된다.
copy[2] = 20
print('\nchanging copy data\n')
print('origin\n', origin)
print('copy\n', copy)
print('deepCopy\n', deepCopy)

# deepCopy는 데이터가 독립적
# 원본이 바뀌어도 deepCopy는 변화 X
# deepCopy가 바뀌어도 원본에 변화 X
deepCopy[3] = 30
print('\nchanging deepCopy data\n')
print('origin\n', origin)
print('copy\n', copy)
print('deepCopy\n', deepCopy)


origin
 [0 1 2 3 4 5]
copy
 [0 1 2 3 4 5]
deepCopy
 [0 1 2 3 4 5]

changing origin data

origin
 [ 0 10  2  3  4  5]
copy
 [ 0 10  2  3  4  5]
deepCopy
 [0 1 2 3 4 5]

changing copy data

origin
 [ 0 10 20  3  4  5]
copy
 [ 0 10 20  3  4  5]
deepCopy
 [0 1 2 3 4 5]

changing deepCopy data

origin
 [ 0 10 20  3  4  5]
copy
 [ 0 10 20  3  4  5]
deepCopy
 [ 0  1  2 30  4  5]


# Data sort / argument sort

In [57]:
a = np.array([3, 2, 5, 1, 4])
print('origin data\n', a)
print('= 0 1 2 3 4 =')

print('\nsorting data\n', np.sort(a)) # np.sort(a)로 값을 정렬
print('after np.sort\n', a) # 원본 데이터에는 변화 X
print('arguments sort\n', np.argsort(a)) # np.argsort(a) => 정렬된 argument 번호로 값을 출력해줌
print('after np.argsort\n', a) # 여전히 원본 데이터는 변화 X

print('argsort method\n', a.argsort())
print('after argsort()\n', a)
a.sort()
print('after sort()\n', a) # a에 직접 a.sort()는 a 원본 데이터 값도 정렬된 상태로 변형시킴

origin data
 [3 2 5 1 4]
= 0 1 2 3 4 =

sorting data
 [1 2 3 4 5]
after np.sort
 [3 2 5 1 4]
arguments sort
 [3 1 0 4 2]
after np.argsort
 [3 2 5 1 4]
argsort method
 [3 1 0 4 2]
after argsort()
 [3 2 5 1 4]
after sort()
 [1 2 3 4 5]
